Cleanup and update of build script and project file.
Signed-off-by: Kathrin Hanauer <kal@xaikal.org>

diff --git a/easyCompile b/easyCompile
--- a/easyCompile
+++ b/easyCompile
@@ -22,16 +22,65 @@
 #   http://algora.xaikal.org                                           #
 ########################################################################
 
+
 export QT_SELECT=qt5
 PRO_FILE="AlgoraDyn.pro"
-#QMAKE="/path/to/qmake"
 
-[ -z "${QMAKE}" ] && QMAKE=$(which qmake 2>/dev/null) && echo "Using ${QMAKE} for \"qmake\"."
-[ -z "${QMAKE}" ] && QMAKE=$(which qmake-qt5 2>/dev/null) && echo "Using ${QMAKE} for \"qmake\"."
-[ -n "${QMAKE}" ] || eval 'echo "Binary \"qmake\" or \"qmake-qt5\"  not found. Please specify its location explicitly via the QMAKE variable." 1>&2; exit 1'
+CLEAN=0
+EXTRA_ARGS=""
+QMAKE=""
+SPEC="linux-g++-64"
 
-QMAKE_ARGS="-r -spec linux-g++-64"
-#QMAKE_ARGS="-r -spec linux-clang"
+function usage() {
+    echo "Usage: $0 [ --qmake <path/to/qmake> ] [ -c | --clean ] [ -g | --general ] [ -d | --debugsymbols] [ -p | --profiling] [ --clang ]"
+}
+
+while [[ $# -gt 0 ]]
+do
+case $1 in
+    --qmake)
+    QMAKE="$2"
+    shift
+    shift
+    ;;
+    -c|--clean)
+    CLEAN=1
+    shift
+    ;;
+    -g|--general)
+    EXTRA_ARGS="${EXTRA_ARGS} CONFIG+=general" # do not optimize for this cpu only
+    shift
+    ;;
+    -d|--debugsymbols)
+    EXTRA_ARGS="${EXTRA_ARGS} CONFIG+=debugsymbols" # add debug symbols in release version
+    shift
+    ;;
+    -p|--profiling)
+    EXTRA_ARGS="${EXTRA_ARGS} CONFIG+=profiling" # enable profiling code
+    shift
+    ;;
+    --clang)
+    SPEC="linux-clang"
+    shift
+    ;;
+    -h|--help)
+    usage
+    exit 0
+    ;;
+    *)
+    echo "Unknown option $1."
+    usage
+    exit 1
+    ;;
+esac
+done
+
+[ -z "${QMAKE}" ] && QMAKE=$(which qmake 2>/dev/null) && echo "Using \"${QMAKE}\" for \"qmake\"."
+[ -z "${QMAKE}" ] && QMAKE=$(which qmake-qt5 2>/dev/null) && echo "Using \"${QMAKE}\" for \"qmake\"."
+[ -n "${QMAKE}" ] || eval 'echo "Binary \"qmake\" or \"qmake-qt5\" not found. Please specify its location explicitly via --qmake <path/to/qmake>." 1>&2; exit 1'
+[ -x "${QMAKE}" ] || eval 'echo "\"${QMAKE}\" is not an executable. Please specify the location of the qmake binary explicitly via --qmake <path/to/qmake>." 1>&2; exit 1'
+
+QMAKE_ARGS="-r -spec ${SPEC} ${EXTRA_ARGS}"
 QMAKE_ARGS_DEBUG="CONFIG+=debug"
 
 
@@ -42,14 +91,10 @@ BUILD_DIR_RELEASE="${BUILD_DIR}/Release"
 
 PRO_PATH="${CUR_DIR}/src/${PRO_FILE}"
 
-if [ "$1" == "-c" -o "$1" == "--clean" ]
+if [ "${CLEAN}" -gt 0 ]
 then
-	echo "Removing build directory as requested..."
+  echo "Removing build directory as requested..."
   rm -rf ${BUILD_DIR}
-elif [ "$#" -gt 0 ]
-then
-	echo "Unsupported option $1".
-	exit 1
 fi
 
 echo "Creating build paths if necessary..."
